#roles/dmz-smtp/handlers/main.yml      

- name: restart postfix
  shell: service postfix restart
  args:
    executable: /bin/bash

- name: restart apache2
  shell: service apache2 restart
  args:
    executable: /bin/bash

- name: postmap transport
  command: postmap /etc/postfix/transport

- name: reload iptables
  shell: iptables-restore < /etc/iptables/rules.v4
  args:
    executable: /bin/bash