#roles/srv-mail/tasks/main.yml 
- name: Installer les paquets nécessaires pour Postfix, Dovecot et MariaDB
  apt:
    name:
      - postfix
      - dovecot-core
      - dovecot-imapd
      - dovecot-pop3d
      - dovecot-ldap
      - mariadb-server
      - postfixadmin
      - postfix-ldap
    state: present
    update_cache: yes

- import_tasks: cert.yml

- name: Déployer la configuration Postfix main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: restart postfix

- name: Déployer la configuration Postfix master.cf
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
  notify: restart postfix

- name: Déployer la configuration sécurisée de Dovecot
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/conf.d/10-ssl.conf
  notify: restart dovecot

- import_tasks: mysql_setup.yml
- import_tasks: postfixadmin.yml
#- import_tasks: dovecot-sql.yml
- import_tasks: dovecot-ldap.yml
- import_tasks: apache_https.yml
